# Jump Sequence Indexing

Notebook version created from `jump-sequence-indexing.py`, preserving the script's sequence, branching, printed row diagnostics, and completion message while adding pandas dataframe displays at the header and output.

```python
Please write a function named solve which accepts two arguments:
  -> jump_sequence: tuple[int, ...] is a sequence of non-negative integers
  -> start_index: int is the index at which you begin traversal of the tuple

Each element in jump_sequence represents the exact distance you can move, in either direction, from that index.
For example—from the start index, you can move to the index calculated by either of the following:
  -> start_index + jump_sequence[start_index]
  -> start_index - jump_sequence[start_index]
From each of the index(es) to which you are able to traverse, you may move in either direction the number of positions represented by the value at that index, repeat ad infinitum.

>> Your objective is to find an element in the tuple with the value 0,
   or determine that reaching an element having the value 0 is not possible.

>> The function should return a bool indicating True if you are able to reach 0,
   or False if it is not possible to reach a position in the tuple holding a 0 value.
Test Cases
```

In [1]:
from fileinput import lineno

import numpy as np
import pandas as pd
from numpy.ma.core import count

# load tuple 1d arrays
sequence_list = [
    (1,(4, 9, 2, 100, 0), 2, True),
    (2,(1, 0, 9, 2, 100, 1), 3, True),
    (3,(0, 9), 1, False),
    (4,(1, 1, 0), 0, True),
    (5,(), 0, False),
    (6,(4, 9, 2, 100, 2), 2, False),
]

# header dataframe display
sequence_df = pd.DataFrame(
    sequence_list,
    columns=["row_number", "nested_tuple", "start_index", "expected_result"],
)
display(sequence_df)

   row_number          nested_tuple  start_index  expected_result
0           1     (4, 9, 2, 100, 0)            2             True
1           2  (1, 0, 9, 2, 100, 1)            3             True
2           3                (0, 9)            1            False
3           4             (1, 1, 0)            0             True
4           5                    ()            0            False
5           6     (4, 9, 2, 100, 2)            2            False

In [2]:
def solve():
    """find an element in the tuple with value 0, or determine not possible."""
    try:
        output_rows = []

        # indexer loop
        for row_sequence in sequence_list:

            # extract meta
            results_dict = {}
            row_number, nested_tuple, start_index, expected_result = row_sequence
            nested_tuple_length = len(nested_tuple)

            # handle edge cases
            if nested_tuple_length < 1:
                jump_value = None
                result_low = None
                result_high = None
                results = [result_low, result_high]

            elif nested_tuple_length < row_sequence[1][start_index]:
                jump_value = None
                result_low = None
                result_high = None
                results = [result_low, result_high]

            else:
                jump_value = row_sequence[1][start_index]
                result_low = nested_tuple[(start_index - jump_value)]
                result_high = nested_tuple[(start_index + jump_value)]
                results = [result_low, result_high]

            # classify outcomes
            if 0 in results:
                outcome = True
            else:
                outcome = False

            concordance = outcome == expected_result

            results_dict["row_number"] = row_number
            results_dict["nested_tuple"] = nested_tuple
            results_dict["nested_tuple_length"] = nested_tuple_length
            results_dict["start_index"] = start_index
            results_dict["jump_value"] = jump_value
            results_dict["result_low"] = result_low
            results_dict["result_high"] = result_high
            results_dict["results"] = results
            results_dict["expected_result"] = expected_result
            results_dict["outcome_result"] = outcome
            results_dict["concordance"] = concordance
            output_rows.append(results_dict)

            # display meta
            print(
                f'\nrow-level tuple: {row_sequence}'
                f'\n    row_number: {row_number}'
                f'\n    nested_tuple length: {nested_tuple_length}'
                f'\n    start_index: {start_index}'
                f'\n    jump_value: {jump_value}'
                f'\n    result_low: {result_low}'
                f'\n    result_high: {result_high}'
                f'\n    results [low, high]: {results}'
                f'\n    expected_result: {expected_result}'
                f'\n    outcome_result: {outcome}'
                f'\n    concordance: {concordance}'
            )

        output_df = pd.DataFrame(output_rows)
        display(output_df)

        return

    except Exception as e_solve:
        print('There was an ERROR: ', e_solve)

    finally:
        print('\n\nThe function solve() has completed.')


solve()

row-level tuple: (1, (4, 9, 2, 100, 0), 2, True)
    row_number: 1
    nested_tuple length: 5
    start_index: 2
    jump_value: 2
    result_low: 4
    result_high: 0
    results [low, high]: [4, 0]
    expected_result: True
    outcome_result: True
    concordance: True

row-level tuple: (2, (1, 0, 9, 2, 100, 1), 3, True)
    row_number: 2
    nested_tuple length: 6
    start_index: 3
    jump_value: 2
    result_low: 0
    result_high: 1
    results [low, high]: [0, 1]
    expected_result: True
    outcome_result: True
    concordance: True

row-level tuple: (3, (0, 9), 1, False)
    row_number: 3
    nested_tuple length: 2
    start_index: 1
    jump_value: None
    result_low: None
    result_high: None
    results [low, high]: [None, None]
    expected_result: False
    outcome_result: False
    concordance: True

row-level tuple: (4, (1, 1, 0), 0, True)
    row_number: 4
    nested_tuple length: 3
    start_index: 0
    jump_value: 1
    result_low: 0
    result_high: 1
    results [low, high]: [0, 1]
    expected_result: True
    outcome_result: True
    concordance: True

row-level tuple: (5, (), 0, False)
    row_number: 5
    nested_tuple length: 0
    start_index: 0
    jump_value: None
    result_low: None
    result_high: None
    results [low, high]: [None, None]
    expected_result: False
    outcome_result: False
    concordance: True

row-level tuple: (6, (4, 9, 2, 100, 2), 2, False)
    row_number: 6
    nested_tuple length: 5
    start_index: 2
    jump_value: 2
    result_low: 4
    result_high: 2
    results [low, high]: [4, 2]
    expected_result: False
    outcome_result: False
    concordance: True

,row_number,nested_tuple,nested_tuple_length,start_index,jump_value,result_low,result_high,results,expected_result,outcome_result,concordance
0,1,"(4, 9, 2, 100, 0)",5,2,2.0,4.0,0.0,"[4, 0]",True,True,True
1,2,"(1, 0, 9, 2, 100, 1)",6,3,2.0,0.0,1.0,"[0, 1]",True,True,True
2,3,"(0, 9)",2,1,NaN,NaN,NaN,"[None, None]",False,False,True
3,4,"(1, 1, 0)",3,0,1.0,0.0,1.0,"[0, 1]",True,True,True
4,5,(),0,0,NaN,NaN,NaN,"[None, None]",False,False,True
5,6,"(4, 9, 2, 100, 2)",5,2,2.0,4.0,2.0,"[4, 2]",False,False,True

The function solve() has completed.